using System.Text.Json;
using ComparisonTool.Core.Serialization.BlazorReport;
using Microsoft.Extensions.Logging;
using Microsoft.JSInterop;

namespace ComparisonTool.Report.Services;

/// <summary>
/// Service that reads the embedded report JSON from the HTML page's script tag
/// and deserializes it into the domain objects that the Blazor UI components consume.
/// </summary>
public sealed class ReportDataService
{
    private readonly IJSRuntime jsRuntime;
    private readonly ILogger<ReportDataService> logger;
    private ReportBootstrapData? cachedData;
    private bool isLoaded;

    public ReportDataService(IJSRuntime jsRuntime, ILogger<ReportDataService> logger)
    {
        this.jsRuntime = jsRuntime;
        this.logger = logger;
    }

    /// <summary>
    /// Gets the loaded report data, or null if not yet loaded.
    /// </summary>
    public ReportBootstrapData? Data => cachedData;

    /// <summary>
    /// Whether the report data has been loaded and deserialized.
    /// </summary>
    public bool IsLoaded => isLoaded;

    /// <summary>
    /// Loads and deserializes the report data from the embedded script tag.
    /// </summary>
    public async Task<ReportBootstrapData> LoadAsync()
    {
        if (isLoaded && cachedData != null)
        {
            return cachedData;
        }

        try
        {
            // Read the JSON content from the <script id="report-data"> tag via a CSP-safe helper
            var json = await jsRuntime.InvokeAsync<string>("getReportData");

            if (string.IsNullOrWhiteSpace(json) || json == "__REPORT_DATA_JSON__")
            {
                throw new InvalidOperationException(
                    "No report data found. This page must be generated by the CLI with embedded comparison results.");
            }

            cachedData = JsonSerializer.Deserialize<ReportBootstrapData>(json, BlazorReportSerializerOptions.Default)
                ?? throw new InvalidOperationException("Failed to deserialize report data.");

            isLoaded = true;
            logger.LogInformation(
                "Report data loaded: {PairCount} pairs, AllEqual={AllEqual}",
                cachedData.Result?.TotalPairsCompared ?? 0,
                cachedData.Result?.AllEqual ?? true);

            return cachedData;
        }
        catch (Exception ex)
        {
            logger.LogError(ex, "Failed to load report data from embedded JSON.");
            throw;
        }
    }
}
