<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ParityBench.NET.Application\ParityBench.NET.Application.csproj" />
    <ProjectReference Include="..\ParityBench.NET.Domain\ParityBench.NET.Domain.csproj" />
    <ProjectReference Include="..\ParityBench.NET.Engine\ParityBench.NET.Engine.csproj" />
    <ProjectReference Include="..\ParityBench.PluginSdk\ParityBench.PluginSdk.csproj" />
  </ItemGroup>

</Project>
