<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <RootNamespace>ComparisonTool.Report</RootNamespace>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" />
        <PackageReference Include="Blazored.LocalStorage" />
        <PackageReference Include="MudBlazor" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ComparisonTool.Core\ComparisonTool.Core.csproj" />
        <ProjectReference Include="..\ComparisonTool.UI\ComparisonTool.UI.csproj" />
    </ItemGroup>

</Project>
